### ISSUE TITLE
Dock Icons / Update Messed Up?

### ISSUE THREAD

**Issue by TRM516** [Muirey03/Zenith#88] opened 2019-05-12 14:40 UTC
Hello, after the new update my dock icons now look like this. They were completely fine before but something cause them to mess up. I have not installed any new tweaks since this update came out that may have caused issues.

![DF298B4F-F1CE-4B10-929A-A52478E0E298](https://user-images.githubusercontent.com/41651078/57583791-bd85ed80-7499-11e9-9e9e-3503f5f29cb6.png)

**Comment by nullcheck** [comment] 2019-05-13 17:41
Same for me when using 1.1.0-2 on iPhone 6S with iOS 12.1.2 and FloatingDock 1.5.
After downgrading to 1.0.9 the issue is gone.

**Comment by TRM516** [comment] 2019-05-13 21:04
nullcheck, how do I downgrade? I’m getting an error when I try. It tells me the expected size mismatches and fails.

**Comment by nullcheck** [comment] 2019-05-16 17:06
@TRM630 I could downgrade just fine using Cydia. Have you tried uninstalling the tweak and re-installing it?
Maybe downgrading works afterwards.

**Comment by Muirey03** [comment] 2019-05-16 18:23
Fixed in v.1.1.1 - available shortly

**Closed as completed by Muirey03** 2019-05-16 18:23 UTC
