### ISSUE TITLE
Moving icons on SpringBoard causes crash

### ISSUE THREAD

**Issue by newuser1234565** [Muirey03/Zenith#75] opened 2019-03-23 15:07 UTC
Here is my crash report. If I move an icon on the SpringBoard it will duplicate itself and then cause my SpringBoard to crash. Every time.

[crash log.txt](https://github.com/Muirey03/Zenith/files/2999499/crash.log.txt)

**Comment by Muirey03** [comment] 2019-04-01 15:05
Can you send the crash report from CrashReporter as well please?

**Comment by newuser1234565** [comment] 2019-04-01 21:11
I don't have a report from that specific crash, unfortunately.

**Comment by Muirey03** [comment] 2019-04-03 13:54
You might have to trigger the crash again to get it reported, but CrashReporter should report all crashes. You haven’t disabled the ReportCrash daemon have you?

**Comment by Muirey03** [comment] 2019-04-15 08:12
Okay, looking at the crash report it looks like this is caused by the same issue as #74 so i'm closing it

**Closed as completed by Muirey03** 2019-04-15 08:12 UTC
